# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  push:
    branches: ['release']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        - name: build arm32v7
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-arm32v7 --build-arg ARCH=arm32v7 --platform linux/arm/v7 .

      - name: push arm32v7
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-arm32v7

      - name: build arm64v8
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-arm64v8 --build-arg ARCH=arm64v8 --platform linux/arm64 .

      - name: push arm64v8
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-arm64v8

      - name: build amd64
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-amd64 --build-arg ARCH=amd64 --platform linux/amd64 .

      - name: push amd64
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-amd64 

      - name: create manifest
        run: docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:release --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-amd64 --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-arm32v7 --amend ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:manifest-arm64v8

      - name: push manifest
        run: docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:release
